### ISSUE TITLE
Support: Can you make a tutorial?

### ISSUE THREAD

**Issue by vaibhavkandwal** [da-edra/dotfiles#1]
Can you make a tutorial for this setup with Arch Linux. From installing Arch to setting up?
Thanks

**Comment by vaibhavkandwal** [comment]
Hello, it's been a while.
Can you help me with this on twitter? I can't send you a message, that's why, opened a request here.
Much Appreciated

**Comment by da-edra** [comment]
Hi @vaibhavkandwal , do you mean a tutorial on how to install Arch?

**Comment by vaibhavkandwal** [comment]
Yes, installing arch, then setting up with this exact config :smiley:

**Comment by da-edra** [comment]
I don't think so, the [Arch Wiki's guide](https://wiki.archlinux.org/index.php/Installation_guide) is really good and contains all of the information you need to install Arch. :smile: 

For my config, you should just install the dependencies listed on the README.md, clone this repo in your $HOME and _voilà_ everything should look and work the same. :smiley:
