### ISSUE TITLE
i3blocks path is missing :(

### ISSUE THREAD

**Issue by sdpb** [da-edra/dotfiles#6]
Hi, da-edra, 
this path "~/.config/i3blocks/blocks/$BLOCK_NAME/$BLOCK_NAME" is missing in your recent update. Could I have your i3block scripts? Please!!.

PD: Your dotfiles are so beautiful, thank you for that :)

**Comment by da-edra** [comment]
Hey @sdpb sorry for taking so long to reply, I've been quite busy lately.
To get the blocks you need to clone them from the official repository `git clone git@github.com:vivien/i3blocks-contrib.git .config/i3blocks/blocks/`, I stopped downloading the blocks and uploading them to the repository as it was somewhat hard to keep them updated.

I'll add this missing step to the documentation, please let me know if it solved your issue.

**Comment by sdpb** [comment]
Yes, that's nice, thanks.
